'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Incoming_Default

    '''<summary>
    '''imgAddAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAddAction As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lnkAddAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddAction As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''imgCancelAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCancelAction As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lnkCancelAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCancelAction As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''notMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notMain As Global.Remi.Controls_Notifications

    '''<summary>
    '''txtRequestUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRequestUnit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valRequestUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valRequestUnit As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''txtBSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBSN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQRANumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQRANumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valQRANumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valQRANumber As Global.System.Web.UI.WebControls.CustomValidator
End Class
