CREATE TABLE [Req].[RequestSetup](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[JobID] [int] NULL,
	[ProductID] [int] NULL,
	[TestStageID] [int] NOT NULL,
	[TestID] [int] NOT NULL,
	[BatchID] [int] NULL,
	[LastUser] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_RequestSetup] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]