'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18063
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class General
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("General", GetType(General).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name of the assigned user must be 255 characters or less..
        '''</summary>
        Friend Shared ReadOnly Property AssignedUserMaxStringLength() As String
            Get
                Return ResourceManager.GetString("AssignedUserMaxStringLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The number entered for the barcode number is not a valid barcode number. A valid barcode is in the format QRA-yy-bbbb-uuu-lllll..
        '''</summary>
        Friend Shared ReadOnly Property BarcodeNumberInvalid() As String
            Get
                Return ResourceManager.GetString("BarcodeNumberInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This is not a valid email address..
        '''</summary>
        Friend Shared ReadOnly Property EmailNotValid() As String
            Get
                Return ResourceManager.GetString("EmailNotValid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name of the geographical location must be 100 characters or less..
        '''</summary>
        Friend Shared ReadOnly Property GeoLocMaxNameLength() As String
            Get
                Return ResourceManager.GetString("GeoLocMaxNameLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to the name of the product group must be 100 characters or less..
        '''</summary>
        Friend Shared ReadOnly Property ProductGroupNameMaxStringLength() As String
            Get
                Return ResourceManager.GetString("ProductGroupNameMaxStringLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The batch cannot be found on the request Databases. Make sure that the batch has been entered in to one of these database (has been processed by incoming) before continuing..
        '''</summary>
        Friend Shared ReadOnly Property ScanDataBatchIsNothing() As String
            Get
                Return ResourceManager.GetString("ScanDataBatchIsNothing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The test unit with this barcode cannot be found on the request Databases. Make sure that the batch has been entered in to one of these database (has been processed by incoming) before continuing..
        '''</summary>
        Friend Shared ReadOnly Property ScanDataTestUnitIsNothing() As String
            Get
                Return ResourceManager.GetString("ScanDataTestUnitIsNothing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The tracking location indicated by this scan cannot be found in the REMI database. Please contact the administrator at remi@blackberry.com..
        '''</summary>
        Friend Shared ReadOnly Property ScanDataTrackingLocationIsNothing() As String
            Get
                Return ResourceManager.GetString("ScanDataTrackingLocationIsNothing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The firmware version must be 100 characters or less..
        '''</summary>
        Friend Shared ReadOnly Property TestStationFirmwareVersionMaxLength() As String
            Get
                Return ResourceManager.GetString("TestStationFirmwareVersionMaxLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The model name must be 100 characters or less..
        '''</summary>
        Friend Shared ReadOnly Property TestStationModelNameMaxLength() As String
            Get
                Return ResourceManager.GetString("TestStationModelNameMaxLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name of the test station must be 100 characters or less..
        '''</summary>
        Friend Shared ReadOnly Property TestStationNameMaxLength() As String
            Get
                Return ResourceManager.GetString("TestStationNameMaxLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The reson for test station schedules must be 255 characters or less..
        '''</summary>
        Friend Shared ReadOnly Property TestStationScheduleReasonMaxLength() As String
            Get
                Return ResourceManager.GetString("TestStationScheduleReasonMaxLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name of the test station type must be 100 characters or less..
        '''</summary>
        Friend Shared ReadOnly Property TestStationTypeNameLength() As String
            Get
                Return ResourceManager.GetString("TestStationTypeNameLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must enter a name for the test station type..
        '''</summary>
        Friend Shared ReadOnly Property TestStationTypeNameNotNullOrEmpty() As String
            Get
                Return ResourceManager.GetString("TestStationTypeNameNotNullOrEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name of the tracking location must be 100 characters or less..
        '''</summary>
        Friend Shared ReadOnly Property TrackingLocationNameMaxStringLength() As String
            Get
                Return ResourceManager.GetString("TrackingLocationNameMaxStringLength", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
