'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18063
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class General
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("General", GetType(General).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not save the item. There was a database error. REMI administrators have been notified..
        '''</summary>
        Public Shared ReadOnly Property e1() As String
            Get
                Return ResourceManager.GetString("e1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The given credentials were not valid and REMI was unable to authenticate this user at LDAP server..
        '''</summary>
        Public Shared ReadOnly Property e10() As String
            Get
                Return ResourceManager.GetString("e10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This batch could not be found in REMI..
        '''</summary>
        Public Shared ReadOnly Property e11() As String
            Get
                Return ResourceManager.GetString("e11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The system could not find a valid user for this scan..
        '''</summary>
        Public Shared ReadOnly Property e12() As String
            Get
                Return ResourceManager.GetString("e12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Test Unit could not be found in REMI..
        '''</summary>
        Public Shared ReadOnly Property e13() As String
            Get
                Return ResourceManager.GetString("e13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The given tracking location could not be found on REMI..
        '''</summary>
        Public Shared ReadOnly Property e14() As String
            Get
                Return ResourceManager.GetString("e14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The scan failed. Review the errors and correct the problem..
        '''</summary>
        Public Shared ReadOnly Property e15() As String
            Get
                Return ResourceManager.GetString("e15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to this test is not valid at this location..
        '''</summary>
        Public Shared ReadOnly Property e16() As String
            Get
                Return ResourceManager.GetString("e16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected test is currently marked DNP. Please ensure you have selected the correct test and test stage for this unit..
        '''</summary>
        Public Shared ReadOnly Property e17() As String
            Get
                Return ResourceManager.GetString("e17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not change the status..
        '''</summary>
        Public Shared ReadOnly Property e18() As String
            Get
                Return ResourceManager.GetString("e18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not validate your username and password. Please try again..
        '''</summary>
        Public Shared ReadOnly Property e19() As String
            Get
                Return ResourceManager.GetString("e19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not delete the item. There was a database error.  REMI administrators have been notified..
        '''</summary>
        Public Shared ReadOnly Property e2() As String
            Get
                Return ResourceManager.GetString("e2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The test currently underway at this location does not match the test you have requested. Please unsure this is the correct test and location for this unit..
        '''</summary>
        Public Shared ReadOnly Property e20() As String
            Get
                Return ResourceManager.GetString("e20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error saving link between Test record and Tracking Log..
        '''</summary>
        Public Shared ReadOnly Property e21() As String
            Get
                Return ResourceManager.GetString("e21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was an error in the user manager. Unable to work with the given user id details..
        '''</summary>
        Public Shared ReadOnly Property e22() As String
            Get
                Return ResourceManager.GetString("e22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not change the RF Bands..
        '''</summary>
        Public Shared ReadOnly Property e23() As String
            Get
                Return ResourceManager.GetString("e23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not generate the random number list. Try again and if the problem persists contact support..
        '''</summary>
        Public Shared ReadOnly Property e24() As String
            Get
                Return ResourceManager.GetString("e24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not retrieve item. There was a database error.  REMI administrators have been notified..
        '''</summary>
        Public Shared ReadOnly Property e3() As String
            Get
                Return ResourceManager.GetString("e3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The test stage for this batch could not be changed. There was a database error..
        '''</summary>
        Public Shared ReadOnly Property e4() As String
            Get
                Return ResourceManager.GetString("e4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not save the item. An with the same parameters is already in the database. Please check the name of the item to confirm it is not already in use..
        '''</summary>
        Public Shared ReadOnly Property e5() As String
            Get
                Return ResourceManager.GetString("e5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was an oracle database error. The remi administrators have been notified..
        '''</summary>
        Public Shared ReadOnly Property e6() As String
            Get
                Return ResourceManager.GetString("e6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not add exception..
        '''</summary>
        Public Shared ReadOnly Property e7() As String
            Get
                Return ResourceManager.GetString("e7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not add unit..
        '''</summary>
        Public Shared ReadOnly Property e8() As String
            Get
                Return ResourceManager.GetString("e8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not add the batch to REMI..
        '''</summary>
        Public Shared ReadOnly Property e9() As String
            Get
                Return ResourceManager.GetString("e9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to URGENT: Fatal application error !!.
        '''</summary>
        Public Shared ReadOnly Property f1() As String
            Get
                Return ResourceManager.GetString("f1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The item was deleted..
        '''</summary>
        Public Shared ReadOnly Property i1() As String
            Get
                Return ResourceManager.GetString("i1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Note: This test unit is currently in Quarantine!.
        '''</summary>
        Public Shared ReadOnly Property i10() As String
            Get
                Return ResourceManager.GetString("i10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The batch Rf Bands were changed..
        '''</summary>
        Public Shared ReadOnly Property i11() As String
            Get
                Return ResourceManager.GetString("i11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The batch comments were updated..
        '''</summary>
        Public Shared ReadOnly Property i12() As String
            Get
                Return ResourceManager.GetString("i12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Record(s)..
        '''</summary>
        Public Shared ReadOnly Property i13() As String
            Get
                Return ResourceManager.GetString("i13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The item was saved OK..
        '''</summary>
        Public Shared ReadOnly Property i2() As String
            Get
                Return ResourceManager.GetString("i2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The current user was not verified with a badge number and does not exist in REMI..
        '''</summary>
        Public Shared ReadOnly Property i3() As String
            Get
                Return ResourceManager.GetString("i3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The capacity for this location  has been reached! Wait for tests to complete or check that devices have not been removed without having been scanned out..
        '''</summary>
        Public Shared ReadOnly Property i4() As String
            Get
                Return ResourceManager.GetString("i4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This batch is in quarantine..
        '''</summary>
        Public Shared ReadOnly Property i5() As String
            Get
                Return ResourceManager.GetString("i5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Note: This test unit is currently part of an FA..
        '''</summary>
        Public Shared ReadOnly Property i6() As String
            Get
                Return ResourceManager.GetString("i6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This unit has already completed testing here. Units should only be tested 3 times for a test..
        '''</summary>
        Public Shared ReadOnly Property i7() As String
            Get
                Return ResourceManager.GetString("i7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The batch status was changed..
        '''</summary>
        Public Shared ReadOnly Property i8() As String
            Get
                Return ResourceManager.GetString("i8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The status of this batch indicates it should not be tested..
        '''</summary>
        Public Shared ReadOnly Property i9() As String
            Get
                Return ResourceManager.GetString("i9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The tracking location type name must be less than 400 characters..
        '''</summary>
        Public Shared ReadOnly Property w1() As String
            Get
                Return ResourceManager.GetString("w1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The job name cannot be empty..
        '''</summary>
        Public Shared ReadOnly Property w10() As String
            Get
                Return ResourceManager.GetString("w10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The product group cannot be empty..
        '''</summary>
        Public Shared ReadOnly Property w11() As String
            Get
                Return ResourceManager.GetString("w11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Priority for the batch must be set before saving..
        '''</summary>
        Public Shared ReadOnly Property w12() As String
            Get
                Return ResourceManager.GetString("w12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing batch status..
        '''</summary>
        Public Shared ReadOnly Property w13() As String
            Get
                Return ResourceManager.GetString("w13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name of the tracking location cannot be empty..
        '''</summary>
        Public Shared ReadOnly Property w14() As String
            Get
                Return ResourceManager.GetString("w14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The tracking location name must be less than 400 characters..
        '''</summary>
        Public Shared ReadOnly Property w15() As String
            Get
                Return ResourceManager.GetString("w15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The geographical location must be set for the tracking location..
        '''</summary>
        Public Shared ReadOnly Property w16() As String
            Get
                Return ResourceManager.GetString("w16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The tracking location status must be set..
        '''</summary>
        Public Shared ReadOnly Property w17() As String
            Get
                Return ResourceManager.GetString("w17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A tracking location must have a type set..
        '''</summary>
        Public Shared ReadOnly Property w18() As String
            Get
                Return ResourceManager.GetString("w18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name of the test must not be empty..
        '''</summary>
        Public Shared ReadOnly Property w19() As String
            Get
                Return ResourceManager.GetString("w19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The tracking location type name cannot be empty..
        '''</summary>
        Public Shared ReadOnly Property w2() As String
            Get
                Return ResourceManager.GetString("w2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name of the test is too long, the name must be less than 400 characters..
        '''</summary>
        Public Shared ReadOnly Property w20() As String
            Get
                Return ResourceManager.GetString("w20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The duration must be between 0 and 99999 hours (1 or 1.8 for example)..
        '''</summary>
        Public Shared ReadOnly Property w21() As String
            Get
                Return ResourceManager.GetString("w21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The test station type must not be empty..
        '''</summary>
        Public Shared ReadOnly Property w22() As String
            Get
                Return ResourceManager.GetString("w22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The WI location is too long, the location must be less than 400 characters..
        '''</summary>
        Public Shared ReadOnly Property w23() As String
            Get
                Return ResourceManager.GetString("w23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The test station type name is too long, the name must be less than 400 characters..
        '''</summary>
        Public Shared ReadOnly Property w25() As String
            Get
                Return ResourceManager.GetString("w25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The test type for a test must be set..
        '''</summary>
        Public Shared ReadOnly Property w26() As String
            Get
                Return ResourceManager.GetString("w26", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name of the test stage cannot be empty..
        '''</summary>
        Public Shared ReadOnly Property w27() As String
            Get
                Return ResourceManager.GetString("w27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name of the test stage must be less than 400 characters..
        '''</summary>
        Public Shared ReadOnly Property w28() As String
            Get
                Return ResourceManager.GetString("w28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The test stage type must be set..
        '''</summary>
        Public Shared ReadOnly Property w29() As String
            Get
                Return ResourceManager.GetString("w29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The capacity for a tracking location type must be set and be greater than 0..
        '''</summary>
        Public Shared ReadOnly Property w3() As String
            Get
                Return ResourceManager.GetString("w3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A test stage must have at least one test..
        '''</summary>
        Public Shared ReadOnly Property w30() As String
            Get
                Return ResourceManager.GetString("w30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name of the job cannot be empty..
        '''</summary>
        Public Shared ReadOnly Property w31() As String
            Get
                Return ResourceManager.GetString("w31", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The name of the job must be less than 400 characters..
        '''</summary>
        Public Shared ReadOnly Property w32() As String
            Get
                Return ResourceManager.GetString("w32", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The comments must be less than 1000 characters..
        '''</summary>
        Public Shared ReadOnly Property w33() As String
            Get
                Return ResourceManager.GetString("w33", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The tracking location for this item could not be found in the tracking location list..
        '''</summary>
        Public Shared ReadOnly Property w34() As String
            Get
                Return ResourceManager.GetString("w34", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The user name entered could not be found on the GAL. Check the name again..
        '''</summary>
        Public Shared ReadOnly Property w35() As String
            Get
                Return ResourceManager.GetString("w35", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The job requested could not be found in the TRS or REMI..
        '''</summary>
        Public Shared ReadOnly Property w36() As String
            Get
                Return ResourceManager.GetString("w36", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The given user has not been given access to scan yet..
        '''</summary>
        Public Shared ReadOnly Property w37() As String
            Get
                Return ResourceManager.GetString("w37", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The tracking location type&apos;s function must be set..
        '''</summary>
        Public Shared ReadOnly Property w38() As String
            Get
                Return ResourceManager.GetString("w38", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The scan direction could not be resolved for this unit..
        '''</summary>
        Public Shared ReadOnly Property w39() As String
            Get
                Return ResourceManager.GetString("w39", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The last user of an object must be set..
        '''</summary>
        Public Shared ReadOnly Property w4() As String
            Get
                Return ResourceManager.GetString("w4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The test unit id must be set for a test record..
        '''</summary>
        Public Shared ReadOnly Property w40() As String
            Get
                Return ResourceManager.GetString("w40", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The job name must be set for a test record..
        '''</summary>
        Public Shared ReadOnly Property w41() As String
            Get
                Return ResourceManager.GetString("w41", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The job name for a test record must be less than 400 characters..
        '''</summary>
        Public Shared ReadOnly Property w42() As String
            Get
                Return ResourceManager.GetString("w42", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The test stage name must be set for a test record..
        '''</summary>
        Public Shared ReadOnly Property w43() As String
            Get
                Return ResourceManager.GetString("w43", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The test stage name for a test record must be less than 400 characters..
        '''</summary>
        Public Shared ReadOnly Property w44() As String
            Get
                Return ResourceManager.GetString("w44", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The test name must be set for a test record..
        '''</summary>
        Public Shared ReadOnly Property w45() As String
            Get
                Return ResourceManager.GetString("w45", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The test name for a test record must be less than 400 characters..
        '''</summary>
        Public Shared ReadOnly Property w46() As String
            Get
                Return ResourceManager.GetString("w46", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The status of the test record must be set..
        '''</summary>
        Public Shared ReadOnly Property w47() As String
            Get
                Return ResourceManager.GetString("w47", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The comments are limited to 1000 characters..
        '''</summary>
        Public Shared ReadOnly Property w48() As String
            Get
                Return ResourceManager.GetString("w48", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unit has already completed testing for this test - Overall Result PASS..
        '''</summary>
        Public Shared ReadOnly Property w49() As String
            Get
                Return ResourceManager.GetString("w49", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The given Request, FA or RIT number is not valid. Please review the given number..
        '''</summary>
        Public Shared ReadOnly Property w5() As String
            Get
                Return ResourceManager.GetString("w5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unit has already completed testing for this test - Overall Result FAIL but with Known Issue..
        '''</summary>
        Public Shared ReadOnly Property w50() As String
            Get
                Return ResourceManager.GetString("w50", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The testing status of this test unit (Not in test) does not allow it to be scanned out of a test. There was a process error..
        '''</summary>
        Public Shared ReadOnly Property w51() As String
            Get
                Return ResourceManager.GetString("w51", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The tracking log test id must be greater than 0..
        '''</summary>
        Public Shared ReadOnly Property w52() As String
            Get
                Return ResourceManager.GetString("w52", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The tracking log tracking location id must be set..
        '''</summary>
        Public Shared ReadOnly Property w53() As String
            Get
                Return ResourceManager.GetString("w53", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The test unit&apos;s tracking log cannot be null..
        '''</summary>
        Public Shared ReadOnly Property w54() As String
            Get
                Return ResourceManager.GetString("w54", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Process error:This unit was last scanned in to a different location. It must be scanned out of this location before being scanned in to a new location..
        '''</summary>
        Public Shared ReadOnly Property w55() As String
            Get
                Return ResourceManager.GetString("w55", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This unit is currently in FA..
        '''</summary>
        Public Shared ReadOnly Property w56() As String
            Get
                Return ResourceManager.GetString("w56", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This unit is not ready to be scanned in for a test. It may not have been scanned out of the last location correctly. If you are scanning out a unit then this may be wrong test station. Check the unit information in REMI (scan for info) to check and contact remi@blackberry.com..
        '''</summary>
        Public Shared ReadOnly Property w57() As String
            Get
                Return ResourceManager.GetString("w57", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This batch is currently on hold and should not be tested..
        '''</summary>
        Public Shared ReadOnly Property w58() As String
            Get
                Return ResourceManager.GetString("w58", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This batch can not be tested due to its current status..
        '''</summary>
        Public Shared ReadOnly Property w59() As String
            Get
                Return ResourceManager.GetString("w59", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The unit number portion of the barcode must be greater than 0..
        '''</summary>
        Public Shared ReadOnly Property w6() As String
            Get
                Return ResourceManager.GetString("w6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not assign the given test stage name, please select the required test stage..
        '''</summary>
        Public Shared ReadOnly Property w60() As String
            Get
                Return ResourceManager.GetString("w60", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This job has no test stages that are applicable to this test station/chamber..
        '''</summary>
        Public Shared ReadOnly Property w61() As String
            Get
                Return ResourceManager.GetString("w61", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The given test could not be set. The test is not part of the given test stage or the tracking location is not valid for this test..
        '''</summary>
        Public Shared ReadOnly Property w62() As String
            Get
                Return ResourceManager.GetString("w62", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are multiple tests available. Manual selection required..
        '''</summary>
        Public Shared ReadOnly Property w63() As String
            Get
                Return ResourceManager.GetString("w63", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The given hostname returns multiple possible locations. You must provide a location ID to use this hostname..
        '''</summary>
        Public Shared ReadOnly Property w64() As String
            Get
                Return ResourceManager.GetString("w64", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The start time must be set..
        '''</summary>
        Public Shared ReadOnly Property w65() As String
            Get
                Return ResourceManager.GetString("w65", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The end time must be set..
        '''</summary>
        Public Shared ReadOnly Property w66() As String
            Get
                Return ResourceManager.GetString("w66", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This hostname is not set to represent a location in remi. You must use a location ID at this hostname..
        '''</summary>
        Public Shared ReadOnly Property w67() As String
            Get
                Return ResourceManager.GetString("w67", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The tracking location function is not set..
        '''</summary>
        Public Shared ReadOnly Property w68() As String
            Get
                Return ResourceManager.GetString("w68", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The trackinglocation id is not set..
        '''</summary>
        Public Shared ReadOnly Property w69() As String
            Get
                Return ResourceManager.GetString("w69", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The barcode is missing the unit number or the tracking location number. The three digit unit number and the 5 digit tracking location number must be present on the barcode for scanning a unit in to a test..
        '''</summary>
        Public Shared ReadOnly Property w7() As String
            Get
                Return ResourceManager.GetString("w7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to REMI indicates that the user could not be resolved. Admin has been notified..
        '''</summary>
        Public Shared ReadOnly Property w70() As String
            Get
                Return ResourceManager.GetString("w70", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Request number cannot be empty..
        '''</summary>
        Public Shared ReadOnly Property w8() As String
            Get
                Return ResourceManager.GetString("w8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Procedure location is too long, the location must be less than 400 characters..
        '''</summary>
        Public Shared ReadOnly Property w80() As String
            Get
                Return ResourceManager.GetString("w80", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TRS Status Is Not Properly Set. This Batch Should not Be Started..
        '''</summary>
        Public Shared ReadOnly Property w81() As String
            Get
                Return ResourceManager.GetString("w81", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Request Number must be valid for a batch..
        '''</summary>
        Public Shared ReadOnly Property w9() As String
            Get
                Return ResourceManager.GetString("w9", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
