'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Search

    '''<summary>
    '''btnTestingComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTestingComplete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnHeld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHeld As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnReporting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReporting As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnIncoming control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIncoming As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rblSearchBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblSearchBy As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''pnlTraining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTraining As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlTestCenterTraining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestCenterTraining As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSearchTraining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSearchTraining As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlUserTraining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUserTraining As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlSearchUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearchUser As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlTestCentersUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestCentersUser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlDepartmentUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDepartmentUser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTraining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTraining As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTrainingLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTrainingLevel As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlProductFilterUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProductFilterUser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkByPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkByPass As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlSearchUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearchUnits As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtBSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBSN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlSearchBatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearchBatch As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlTestCenters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestCenters As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDepartment As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlProductFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProductFilter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkShowArchived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowArchived As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtRevision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRevision As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlProductType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProductType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlAccessoryGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccessoryGroup As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlRequestReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRequestReason As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlJobs As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTestStages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestStages As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTestStage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTestStage As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlTestStageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestStageType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkTestStageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTestStageType As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''ddlTests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTests As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlBatchStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBatchStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkBatchStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBatchStatus As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''ddlPriority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPriority As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUsers As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTrackingLocationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTrackingLocationType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlLocationFunction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLocationFunction As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlNotInLocationFunction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNotInLocationFunction As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStart As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtStart_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStart_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEnd_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnd_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''pnlSearchExceptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearchExceptions As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlTestCentersException control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestCentersException As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlProductFilter2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProductFilter2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlProductType2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProductType2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlAccesssoryGroup2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccesssoryGroup2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlJobs2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlJobs2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTestStages2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestStages2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTests2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTests2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlRequestReasonException control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRequestReasonException As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkIsMQual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIsMQual As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkIncludeBatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncludeBatch As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtQRANumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQRANumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valQRANumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valQRANumber As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''pnlSearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearchResults As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''updResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updResults As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlTestCenterRQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestCenterRQ As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkShowOnlyFailValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowOnlyFailValue As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkProductFilterRQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkProductFilterRQ As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''chkJobsRQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkJobsRQ As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''chkStagesRQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStagesRQ As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''ddlTestsResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestsResults As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlMeasurementType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMeasurementType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlParameter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlParameterValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlParameterValue As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''upResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upResults As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''pnlKPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlKPI As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtStartKPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartKPI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender3 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtEndKPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEndKPI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender4 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''ddlTestCenterKPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestCenterKPI As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlKPIType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlKPIType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''updProcessing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updProcessing As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSearching control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearching As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lnkExportAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkExportAction As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''notMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notMain As Global.Remi.Controls_Notifications

    '''<summary>
    '''gvwTraining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwTraining As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvwUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwUsers As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvwRQResultsTrend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwRQResultsTrend As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvwKPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwKPI As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvwTestExceptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwTestExceptions As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblTopInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTopInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''bscMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bscMain As Global.Remi.Controls_BatchSelectControl

    '''<summary>
    '''gvwUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwUnits As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''upProcessing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upProcessing As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''odsTraining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsTraining As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsTrainingLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsTrainingLevel As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsTests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsTests As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsJobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsJobs As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''odsTestCenters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsTestCenters As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
