ALTER TABLE [dbo].[TestExceptions] ADD  CONSTRAINT [PK_TestExceptions] PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[LookupID] ASC
)WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);