'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TestRecords_EditDetail

    '''<summary>
    '''li control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgTestRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgTestRecords As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''hypTestRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypTestRecords As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''hypBatchInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypBatchInfo As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''notMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notMain As Global.Remi.Controls_Notifications

    '''<summary>
    '''pnlDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDetails As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblResultText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResultText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''grdTrackingLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdTrackingLog As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsTrackingLogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsTrackingLogs As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''lblReTestCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReTestCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlResultStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlResultStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''odsResultStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsResultStatus As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''rblMFISFIAcc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblMFISFIAcc As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rptDocList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptDocList As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptFAList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptFAList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''txtAssignAnyFailDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAssignAnyFailDoc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAssignAnyFailDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAssignAnyFailDoc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hypAddNewFA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypAddNewFA As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypAddNewRIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypAddNewRIT As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypAddNewSCM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypAddNewSCM As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''chkApplyToSimilarResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkApplyToSimilarResults As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnDetailDone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDetailDone As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDetailCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDetailCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdnTestRecordLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTestRecordLink As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnQRANumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnQRANumber As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnBatchID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnBatchID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnproductGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnproductGroup As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnTRID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTRID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnTestID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTestID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnTestStageID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTestStageID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnUnitID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnUnitID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''grdAuditLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAuditLog As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsAuditLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsAuditLog As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''pnlRelabMatrix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRelabMatrix As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvwRelabMatrix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwRelabMatrix As Global.System.Web.UI.WebControls.GridView
End Class
