SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER FUNCTION dbo.remifnTestCanDelete (@TestID INT)
RETURNS BIT
AS
BEGIN
	DECLARE @Exists BIT
	
	SELECT @Exists = (SELECT DISTINCT 0
		FROM ProductConfigurationUpload
		WHERE TestID=@TestID
		UNION
		SELECT DISTINCT 0
		FROM BatchSpecificTestDurations
		WHERE TestID=@TestID
		UNION
		SELECT DISTINCT 0
		FROM Relab.Results
		WHERE TestID=@TestID
		UNION
		SELECT DISTINCT 0
		FROM TestRecords
		WHERE TestID=@TestID)
	
	RETURN ISNULL(@Exists, 1)
END
GO
GRANT EXECUTE ON remifnTestCanDelete TO Remi
GO