'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BadgeAccess_Default

    '''<summary>
    '''notMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notMain As Global.Remi.Controls_Notifications

    Protected WithEvents mvLogin As Global.System.Web.UI.WebControls.MultiView
    Protected WithEvents cvBadge As Global.System.Web.UI.WebControls.CompareValidator
    Protected WithEvents cvNewBadge As Global.System.Web.UI.WebControls.CompareValidator

    Protected WithEvents rfvUserName As Global.System.Web.UI.WebControls.RequiredFieldValidator
    Protected WithEvents rfvPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnlogin As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnCreate As Global.System.Web.UI.WebControls.Button
    '''<summary>
    '''txtUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUserName As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtNewUserName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valUserName As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''txtPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtNewPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valPassword As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''ddlGeoLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGeoLoc As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''odsTestCentres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsTestCentres As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''ddlDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDepartments As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''odsDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDepartments As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''txtBadge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBadge As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtNewBadge As Global.System.Web.UI.WebControls.TextBox
End Class
