'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ES_Default

    '''<summary>
    '''lblPH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPH As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ESMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ESMenu As Global.System.Web.UI.WebControls.Menu

    '''<summary>
    '''hdnBatchID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnBatchID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnRequestNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnRequestNumber As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cpeRequestInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpeRequestInfo As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''cpeFA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpeFA As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''cpeRequestSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpeRequestSummary As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''cpeApprovals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpeApprovals As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''lblRequestNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrinted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrinted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlES As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblES As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblESText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblESText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdJIRAS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdJIRAS As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnlRequestSummaryHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRequestSummaryHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSummary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgRequestSummaryExpCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgRequestSummaryExpCol As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlRequestSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRequestSummary As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''hdnPartName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPartName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''rptRequestSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptRequestSummary As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlRequestInfoHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRequestInfoHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgExpCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgExpCol As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlRequestInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRequestInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvwRequestInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwRequestInfo As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''updResultBreakdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updResultBreakdown As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''upResultBreakdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upResultBreakdown As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''cpeResultSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpeResultSummary As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''cpeResultBreakDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpeResultBreakDown As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''cpeObservations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpeObservations As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''cpeObservationSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpeObservationSummary As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''pnlQRASlider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlQRASlider As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rboQRASlider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rboQRASlider As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''pnlResultSummaryHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResultSummaryHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblResultSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResultSummary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgResultSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgResultSummary As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlResultSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResultSummary As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvwResultSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwResultSummary As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsResultSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsResultSummary As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''pnlResultBreakdownHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResultBreakdownHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblResultBreakDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResultBreakDown As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgResultBreakDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgResultBreakDown As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlResultBreakDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResultBreakDown As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvwResultBreakDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwResultBreakDown As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsResultBreakdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsResultBreakdown As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''pnlObservationSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlObservationSummary As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblbservationSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbservationSummary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgObservationSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgObservationSummary As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlObservationSummaryInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlObservationSummaryInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvwObservationSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwObservationSummary As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsObservations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsObservations As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''pnlObservations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlObservations As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblbservations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbservations As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgObservations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgObservations As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlObservationsInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlObservationsInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvwObservations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvwObservations As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''odsObservationInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsObservationInfo As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''pnlFA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFA As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblFA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgFA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgFA As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlFAInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFAInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlFailures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFailures As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlApprovalHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlApprovalHeader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApprove As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgApprovals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgApprovals As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlApproval As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''grdApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdApproval As Global.System.Web.UI.WebControls.GridView
End Class
