CREATE UNIQUE NONCLUSTERED INDEX [UX_JobOrientation_JID_PID_Name] ON [dbo].JobOrientation 
(
	JobID ASC,
	ProductTypeID ASC,
	Name ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO