CREATE TABLE [dbo].[ApplicationProductVersion](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AppVersionID] [int] NOT NULL,
	[PCVID] [int] NOT NULL,
 CONSTRAINT [PK_ApplicationProductVersion] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]