CREATE TABLE [dbo].[TargetAccess](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TargetName] [nvarchar](50) NOT NULL,
	[DenyAccess] [bit] NOT NULL,
	WorkstationName NVARCHAR(50) NULL,
 CONSTRAINT [PK_TargetAccess] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UX_TargetAccess_TargetName] UNIQUE NONCLUSTERED 
(
	[TargetName] ASC,WorkstationName
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TargetAccess] ADD  CONSTRAINT [DF_TargetAccess_DenyAccess]  DEFAULT ((0)) FOR [DenyAccess]
GO