ALTER TABLE [dbo].[RFBands]
    ADD CONSTRAINT [PK_RFBands] PRIMARY KEY CLUSTERED ([ProductGroupName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

